# Trino Log Configuration

com.facebook.presto=INFO
com.facebook.airlift.http=INFO
com.facebook.airlift.json=INFO
com.facebook.cache=INFO
com.facebook.drift=INFO
com.facebook.jmx=INFO
com.facebook.stats=INFO
com.facebook.wire=INFO
io.airlift.bootstrap=INFO
org.eclipse.jetty=INFO
